In [2]:
%cd ..

F:\Projects\GraphRouterV2

C:\Users\CMG\AppData\Roaming\Python\Python312\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [3]:
import pandas as pd
import numpy as np

In [4]:
router_df = pd.read_csv('datasets/200Q-Final/router_training_data.csv')
router_df.head()

,row_id,query_id,task_description,task_description_embedding,query,query_embedding,Gold_Answer,Answer_Type,model,Predicted_Answer,...,Output_Tokens,Total_Tokens,Cost,Latency,Completion_Status,Error_Type,Final_Answer_Length,Timestamp,reasoning_score,response
0,80646b9ac545,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,openai/gpt-5,336,...,610,767,0.006296,10.213,success,wrong_answer,3,2026-06-22T11:33:24.397321+00:00,NaN,FINAL_ANSWER:\n336
1,d6e6c6d24304,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,anthropic/claude-sonnet-4-5,336,...,221,403,0.003861,6.291,success,wrong_answer,3,2026-06-22T11:33:44.699876+00:00,NaN,I need to find the number of ways to divide 10...
2,0b544c46ca65,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,qwen/qwen3-235b-a22b,$$,...,283,444,0.000588,5.144,success,wrong_answer,2,2026-06-22T11:34:47.171332+00:00,NaN,To divide 10 girls into two groups with **at l...
3,00c055cf04a2,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,meta-llama/llama-3.1-70b-instruct,\binom{10}{4} + \binom{10}{5},...,22,183,0.000073,1.730,success,none,29,2026-06-22T11:35:06.160700+00:00,NaN,FINAL_ANSWER: \binom{10}{4} + \binom{10}{5}
4,3a780bd77dc7,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,mistralai/mixtral-8x22b-instruct,115,...,11,186,0.000167,1.981,success,wrong_answer,3,2026-06-22T11:35:20.612191+00:00,NaN,FINAL_ANSWER:\n115

# Scoring Measure

In [5]:
import json
# File I/O functions
def loadjson(filename: str) -> dict:
    """
    Load data from a JSON file.

    Args:
        filename: Path to the JSON file

    Returns:
        Dictionary containing the loaded JSON data
    """
    with open(filename, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data

llm_path = "datasets/200Q-Final/LLM_Descriptions.json"
num_llms = 7
llm_description = loadjson(llm_path)
llm_names = list(llm_description.keys())

def _enforce_rectangular_query_blocks(df: pd.DataFrame) -> pd.DataFrame:
    """
    Guarantee the invariant every downstream positional index relies on:
    each query occupies exactly self.num_llms consecutive rows, one per
    distinct model value found in the router data. Groups by `query_id`
    (present in router_data.csv per Revised_Feature_Plan.md); falls back
    to grouping by raw `query` text with a warning if query_id is missing.

    The "complete set" of models is derived from the router dataset's own
    `model` column (self-consistency check), NOT compared against
    LLM_Descriptions.json's llm_names -- the two use unrelated naming
    schemes and matching them is a separate concern from data integrity.
    The one thing we do verify is that the router data's own model
    vocabulary has exactly self.num_llms distinct values, since that's
    the cardinality every downstream tensor shape assumes.

    Any query_id whose row set doesn't cover that vocabulary exactly once
    (missing run, duplicate run) is DROPPED WHOLESALE and reported --
    keeping it would silently misalign edge_org_id/edge_des_id/
    unique_index_list for every query after it, which is strictly worse
    than losing that one query's data.
    """
    group_col = "query_id" if "query_id" in df.columns else "query"
    if group_col == "query":
        print("[data_integrity][WARN] no query_id column found -- grouping by raw "
              "query text instead. If two different queries have identical text this "
              "will incorrectly merge them.")

    wanted_models = sorted(df["model"].unique().tolist())
    if len(wanted_models) != num_llms:
        raise ValueError(
            f"[data_integrity] router_data's `model` column has {len(wanted_models)} distinct "
            f"values {wanted_models}, but LLM_Descriptions.json declares {num_llms} LLMs "
            f"({llm_names}). These counts must match -- check for typos/extra models in "
            f"the data or a stale LLM_Descriptions.json."
        )
    wanted_models_set = set(wanted_models)
    llm_order = {name: i for i, name in enumerate(wanted_models)}  # stable order, data-derived

    kept_blocks = []
    n_dropped_queries = 0
    dropped_ids = []
    for key, group in df.groupby(group_col, sort=False):
        models_here = group["model"].tolist()
        if len(models_here) != num_llms or set(models_here) != wanted_models_set:
            n_dropped_queries += 1
            dropped_ids.append(key)
            continue
        kept_blocks.append(group.assign(_llm_sort=group["model"].map(llm_order)).sort_values("_llm_sort"))

    if n_dropped_queries:
        preview = dropped_ids[:10]
        print(f"[data_integrity][WARN] dropped {n_dropped_queries} incomplete/duplicate "
              f"query group(s) out of {df[group_col].nunique()} -- these queries did not "
              f"have exactly one row per model in {wanted_models}. Example query_id(s): {preview}"
              f"{' ...' if n_dropped_queries > 10 else ''}")

    if not kept_blocks:
        raise ValueError(
            "[data_integrity] 0 complete query blocks after filtering -- check the `model` "
            "column values in router_data.csv for typos/inconsistent naming: " + str(wanted_models)
        )

    result = pd.concat(kept_blocks, axis=0, ignore_index=True).drop(columns=["_llm_sort"])
    n_before, n_after = len(df), len(result)
    print(f"[data_integrity] rectangular-block check: {n_before} -> {n_after} rows "
          f"({n_before - n_after} dropped), {n_after // num_llms} complete queries retained.")
    return result

In [6]:
router_df = _enforce_rectangular_query_blocks(router_df)
router_df.shape

[data_integrity][WARN] dropped 22 incomplete/duplicate query group(s) out of 98 -- these queries did not have exactly one row per model in ['anthropic/claude-sonnet-4-5', 'deepseek/deepseek-r1', 'google/gemini-3.5-flash', 'meta-llama/llama-3.1-70b-instruct', 'mistralai/mixtral-8x22b-instruct', 'openai/gpt-5', 'qwen/qwen3-235b-a22b']. Example query_id(s): ['8ff9e9f62f23', 'e95fa790cb93', '9097abd21c8e', '7208ad940d2c', '437120961e45', '8600dcc5546d', '70629b6e7c5d', '84c96fbdf01d', '015197614be4', '290f22cd04ea'] ...
[data_integrity] rectangular-block check: 664 -> 532 rows (132 dropped), 76 complete queries retained.

(532, 22)

In [7]:
router_df

,row_id,query_id,task_description,task_description_embedding,query,query_embedding,Gold_Answer,Answer_Type,model,Predicted_Answer,...,Output_Tokens,Total_Tokens,Cost,Latency,Completion_Status,Error_Type,Final_Answer_Length,Timestamp,reasoning_score,response
0,d6e6c6d24304,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,anthropic/claude-sonnet-4-5,336,...,221,403,0.003861,6.291,success,wrong_answer,3,2026-06-22T11:33:44.699876+00:00,NaN,I need to find the number of ways to divide 10...
1,5832db75e144,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,deepseek/deepseek-r1,336,...,5841,5998,0.014712,204.084,success,wrong_answer,3,2026-06-22T12:52:07.306918+00:00,NaN,The number of ways to divide 10 distinct girls...
2,acca4d08183e,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,google/gemini-3.5-flash,336,...,786,948,0.007317,5.973,success,wrong_answer,3,2026-06-22T12:51:49.776277+00:00,NaN,FINAL_ANSWER:\n336
3,00c055cf04a2,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,meta-llama/llama-3.1-70b-instruct,\binom{10}{4} + \binom{10}{5},...,22,183,0.000073,1.730,success,none,29,2026-06-22T11:35:06.160700+00:00,NaN,FINAL_ANSWER: \binom{10}{4} + \binom{10}{5}
4,3a780bd77dc7,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,mistralai/mixtral-8x22b-instruct,115,...,11,186,0.000167,1.981,success,wrong_answer,3,2026-06-22T11:35:20.612191+00:00,NaN,FINAL_ANSWER:\n115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,84a94d01efc4,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,google/gemini-3.5-flash,540,...,747,892,0.006940,4.365,success,none,3,2026-07-01T00:47:14.814064+00:00,NaN,FINAL_ANSWER:\n540
528,c0fbd2d28827,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,meta-llama/llama-3.1-70b-instruct,\sqrt{117^2+144^2}+75\cdot4,...,21,163,0.000065,3.502,success,none,27,2026-07-01T00:47:49.400257+00:00,NaN,FINAL_ANSWER:\n\sqrt{117^2+144^2}+75\cdot4
529,a938cced6691,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,mistralai/mixtral-8x22b-instruct,135,...,11,167,0.000150,1.170,success,wrong_answer,3,2026-07-01T00:47:54.936346+00:00,NaN,FINAL_ANSWER:\n135
530,adb08f542d48,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,openai/gpt-5,540,...,1420,1560,0.014375,28.248,success,none,3,2026-06-30T23:27:38.981802+00:00,NaN,FINAL_ANSWER:\n540
531,a1718526e127,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,qwen/qwen3-235b-a22b,NaN,...,2731,2877,0.005037,30.160,success,none,0,2026-07-01T00:47:19.210218+00:00,NaN,To find the **largest possible real part** of ...

In [8]:
from data_processing import feature_builder as fb

encoders = fb.fit_encoders(
    router_df,
)

[feature_builder] 'Answer_Type' is constant ('latex') in the train split -- dropped (0 dims) instead of encoded as a dead-weight one-hot column.

In [9]:
encoders

FeatureEncoders(domain_categories=['Combinatorics_Discrete', 'Number_Theory', 'Algebra', 'Geometry', 'Olympiad_Logic', 'Other'], domain_precomputed_columns=[], reasoning_type_categories=[], difficulty_categories=[], difficulty_ordinal_order=None, difficulty_is_numeric=False, difficulty_mu_sigma=(0.0, 1.0), reasoning_depth_categories=[], reasoning_depth_ordinal_order=None, reasoning_depth_is_numeric=False, reasoning_depth_mu_sigma=(0.0, 1.0), answer_type_categories=[], solution_steps_mu_sigma=(0.0, 1.0), question_length_mu_sigma=(5.580089635700915, 0.6565240740686119), completion_status_categories=['success'], error_type_categories=['no_final_answer', 'none', 'wrong_answer'], cost_mu_sigma=(0.015854302011278198, 0.035626543814508485), latency_mu_sigma=(79.98872744360904, 222.38950959158626), input_tokens_mu_sigma=(274.49436090225566, 1107.6739709445421), output_tokens_mu_sigma=(2716.281954887218, 5789.296793576096), completion_reliability_by_model={'anthropic/claude-sonnet-4-5': 0.0, 'deepseek/deepseek-r1': 0.0, 'google/gemini-3.5-flash': 0.0, 'meta-llama/llama-3.1-70b-instruct': 0.0, 'mistralai/mixtral-8x22b-instruct': 0.0, 'openai/gpt-5': 0.0, 'qwen/qwen3-235b-a22b': 0.0})

In [10]:
utility_weights = {
  "w_success": 1.0,
  "w_cost": 0.3,
  "w_latency": 0.3,
  "w_output_tokens": 0.2,
  "w_completion_reliability": 0.5
    }

In [11]:
len(router_df.model.unique())

7

In [12]:
edge_features = fb.build_edge_features(router_df, encoders)
edge_features

array([[ 0.        , -0.3366395 , -0.3313903 , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        , -0.032052  ,  0.5580087 , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        , -0.23963319, -0.33282024, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 0.        , -0.440795  , -0.35441747, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , -0.04152247, -0.23265813, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.        , -0.3036346 , -0.2240606 , ...,  0.        ,
         1.        ,  0.        ]], dtype=float32)

In [13]:
utility_list = fb.compute_utility(router_df, encoders, **utility_weights)
utility_list

array([ 2.86612213e-01, -2.65735090e-01,  2.38420531e-01,  1.33153558e+00,
        3.30783755e-01,  2.47376442e-01,  3.13575834e-01,  2.16807097e-01,
       -9.80435610e-01,  1.71236560e-01,  1.33137298e+00,  1.33004844e+00,
        1.20127141e+00,  1.30528224e+00,  2.15351030e-01, -6.03930891e-01,
        1.27695918e-01,  3.32691073e-01,  3.30899507e-01,  2.68264115e-01,
        3.30785602e-01,  1.21945786e+00,  2.78333724e-01,  1.10919797e+00,
        3.32728237e-01,  3.30041587e-01,  3.24955732e-02,  2.90302843e-01,
        1.26425862e+00,  1.21454120e+00,  1.27155805e+00,  1.32555819e+00,
        1.32704103e+00,  1.25782645e+00,  3.13551426e-01,  1.25015557e+00,
        7.08641231e-01,  1.25199986e+00,  3.32814276e-01,  3.28209281e-01,
        1.22744668e+00,  1.29980445e+00,  1.47536650e-01,  7.75919437e-01,
        1.08020163e+00,  1.32810223e+00,  3.31502885e-01,  1.09791017e+00,
        1.22963345e+00,  1.75550237e-01,  2.26218104e-01,  1.79758862e-01,
        1.33048785e+00,  3.26230764e-01,  1.76268935e-01,  3.27849448e-01,
        1.27447641e+00,  1.29416919e+00,  1.28252316e+00,  3.31766754e-01,
        1.32948446e+00,  1.29358852e+00,  3.28482270e-01,  1.17287612e+00,
       -5.21478117e-01,  1.27279431e-01,  3.29870820e-01,  3.30760121e-01,
       -4.07829918e-02,  2.47538373e-01,  1.77832931e-01,  3.86964232e-01,
        1.18651426e+00,  1.32896650e+00,  1.33133852e+00,  1.06557882e+00,
        3.30167443e-01,  1.25060928e+00,  1.22004986e+00,  1.28417170e+00,
        1.33088827e+00,  1.33120489e+00,  1.21196461e+00,  1.33090830e+00,
        1.93196848e-01,  2.84211814e-01,  4.38739136e-02,  3.32141429e-01,
        3.31812114e-01,  2.78272063e-01,  3.28736752e-01,  1.73753873e-01,
       -1.77083600e+00,  3.66379172e-02,  3.32100034e-01,  3.30012560e-01,
        5.46997070e-01,  3.29940706e-01,  1.56126052e-01,  4.17077065e-01,
        1.18904546e-01,  3.29443574e-01,  3.28013659e-01, -8.76092374e-01,
        1.97512254e-01,  1.67539522e-01, -2.67968845e+00,  3.78886797e-02,
        3.30838680e-01,  3.30559433e-01,  2.61727035e-01,  1.32819843e+00,
        1.24198604e+00, -7.18963027e-01,  1.20385444e+00,  1.32943583e+00,
        3.28782111e-01, -3.89737725e-01,  1.32854819e+00,  1.91457629e-01,
       -2.73036695e+00,  3.49757224e-02,  3.27860981e-01,  1.32887113e+00,
       -4.97891092e+00,  1.32994676e+00,  1.88711271e-01, -1.41708672e+00,
        1.15334082e+00,  3.29391241e-01,  3.30604851e-01, -2.11748052e+00,
        3.17330956e-01,  1.14586949e+00, -5.31023502e-01,  4.03884389e-02,
        3.27256799e-01,  3.26690614e-01, -5.74362946e+00,  1.32764161e+00,
        1.10808842e-01,  1.51853114e-01,  1.15026975e+00,  1.33047748e+00,
        3.28614771e-01,  1.11769879e+00,  2.01742023e-01,  1.19041848e+00,
        9.00815666e-01,  1.24241650e+00,  3.30331326e-01,  3.30448359e-01,
        1.16740012e+00,  1.27276623e+00,  1.61611751e-01, -2.94329971e-01,
        4.64397632e-02,  3.31114054e-01,  3.30036849e-01, -3.20694625e-01,
        3.30585897e-01,  1.49221003e-01, -3.11852407e+00,  3.10307331e-02,
        3.31626564e-01,  3.29137862e-01, -3.40812659e+00,  3.29216182e-01,
        9.29828547e-03,  3.09681118e-01,  3.32269482e-02,  3.30550551e-01,
        3.29369962e-01,  9.46085274e-01,  3.25795084e-01,  1.21747935e+00,
        1.21684992e+00,  1.25804901e+00,  3.20073843e-01,  3.25502187e-01,
        1.21312463e+00,  2.99030870e-01,  1.20681846e+00, -5.33938527e-01,
        1.17418730e+00,  1.32924819e+00,  3.20214748e-01,  1.04566026e+00,
        2.65886486e-01,  1.12667847e+00,  3.11074048e-01,  3.88985500e-02,
        3.30754369e-01,  3.18747520e-01,  1.07876647e+00,  1.83725327e-01,
        1.40469953e-01, -1.37772393e+00,  1.04445171e+00,  3.28158408e-01,
        3.30065459e-01,  4.16683674e-01,  3.28586519e-01,  1.21953857e+00,
        8.37573290e-01,  1.14872479e+00,  3.32348764e-01,  3.31439555e-01,
        1.17731237e+00,  3.07257682e-01,  1.10468876e+00, -1.38352001e+00,
        3.56811285e-02,  3.31328362e-01,  3.30577821e-01, -6.32927835e-01,
        3.30522865e-01,  1.17958319e+00,  2.16215163e-01,  1.13565397e+00,
        3.30672294e-01,  3.31794262e-01,  1.10384440e+00,  2.99182832e-01,
        1.67449847e-01, -1.47398770e+00, -2.87424680e-02,  3.31472605e-01,
        3.31019074e-01, -1.02043355e+00,  3.30878705e-01,  1.39764354e-01,
       -1.12848125e-01,  3.26266050e-01,  3.31783742e-01,  3.31607848e-01,
        6.93933129e-01,  3.31394136e-01,  1.74541742e-01,  8.83691758e-02,
        1.12472618e+00,  3.32511187e-01,  3.31954062e-01,  8.88486326e-01,
        3.30444962e-01,  1.13630366e+00, -8.92607346e-02,  8.73798728e-01,
        3.27762157e-01,  3.30619305e-01,  7.00587511e-01,  3.31156254e-01,
        1.12443793e+00,  2.04552382e-01,  1.23513472e+00,  3.27408880e-01,
        3.30860466e-01,  1.11658883e+00,  3.29492509e-01,  9.93431926e-01,
       -7.48878717e-02,  9.88871932e-01,  1.33027661e+00,  3.29183161e-01,
        1.04896045e+00,  3.28227639e-01,  9.01319366e-03, -1.51013088e+00,
        1.13121498e+00,  3.31632316e-01,  3.31420660e-01,  2.29348049e-01,
        3.32418859e-01,  1.23821795e+00,  1.09124327e+00,  1.26918650e+00,
        3.31278861e-01,  3.31364006e-01,  1.28508317e+00,  3.30404848e-01,
        9.58021462e-01,  6.61173165e-01,  1.21676672e+00,  3.30133736e-01,
        3.29681695e-01,  1.17198408e+00,  3.29212219e-01,  1.16885960e+00,
       -2.17801821e-03,  1.27840447e+00,  1.33083117e+00,  3.28311354e-01,
        1.13957930e+00,  3.29232931e-01,  1.11545169e+00,  4.70694721e-01,
        1.24400842e+00,  3.28819275e-01,  3.29965323e-01,  1.27095366e+00,
        3.31011981e-01,  2.58303881e-01, -1.26599863e-01,  9.32760835e-01,
        3.29715729e-01,  3.32570195e-01,  2.69272357e-01,  7.81350061e-02,
        1.21961808e+00,  6.24305785e-01,  1.28551686e+00,  3.29342335e-01,
        3.29419941e-01,  1.24923754e+00,  3.30887198e-01,  9.96774435e-01,
        7.22455084e-01,  1.22737002e+00,  3.30480605e-01,  3.32065463e-01,
        1.06583416e+00,  3.30694616e-01,  9.24683392e-01,  7.83174932e-01,
        1.19755125e+00,  3.31075191e-01,  3.29112172e-01,  1.10500085e+00,
        3.32567632e-01,  7.34348297e-01,  4.37614948e-01,  1.14639628e+00,
        1.33223283e+00,  3.30696195e-01,  8.07826698e-01,  3.31149697e-01,
        1.11857605e+00,  7.52082944e-01,  1.23187268e+00,  3.31374735e-01,
        3.31252366e-01,  8.78899813e-01,  3.29228669e-01,  1.16821110e+00,
       -4.00026031e-02,  1.18307602e+00,  1.33157587e+00,  3.29177499e-01,
        6.66742980e-01,  3.29684138e-01,  1.09620798e+00,  9.48160708e-01,
        1.23173761e+00,  1.33282733e+00,  3.32343519e-01,  1.11756110e+00,
        3.31084013e-01,  3.82490898e-03, -9.28536475e-01,  1.01981664e+00,
        1.33202970e+00,  3.31755280e-01, -3.13362367e-02,  3.28937978e-01,
       -3.16291809e-01, -4.99754436e-02,  1.18252888e-01,  1.32382321e+00,
        3.29965055e-01,  2.80159891e-01,  1.33086729e+00,  1.24700809e+00,
        8.00206423e-01,  1.26493764e+00,  1.32792115e+00,  3.30624759e-01,
        1.24749005e+00,  3.31747055e-01, -3.81918073e-01, -3.86015129e+00,
        7.70686328e-01,  1.33060980e+00,  3.29855561e-01, -4.21654172e-02,
        3.31539303e-01,  1.25573647e+00,  1.21812522e+00,  1.30588090e+00,
        1.33000934e+00,  3.29919904e-01,  1.27152240e+00,  1.32835591e+00,
        1.21193421e+00,  8.53848338e-01,  1.26952064e+00,  1.33020902e+00,
        3.32253784e-01,  1.20402861e+00,  1.32226491e+00, -3.18025917e-01,
       -2.78223109e+00,  9.66265559e-01,  1.33110762e+00,  3.29731375e-01,
        2.92577684e-01,  3.29290360e-01,  1.21906757e+00,  1.00429356e+00,
        1.28079307e+00,  3.22897196e-01,  3.30838889e-01,  1.25444698e+00,
        3.29979926e-01,  1.07450950e+00,  8.13667834e-01,  1.30386448e+00,
        1.33142602e+00,  1.33048856e+00,  1.22296345e+00,  1.33062720e+00,
        1.11910772e+00,  4.78674412e-01,  1.20440698e+00,  1.33147967e+00,
        1.33153808e+00,  9.20976758e-01,  3.30676675e-01,  1.08833432e+00,
        8.45157981e-01,  1.18671715e+00,  3.28875542e-01,  3.32370877e-01,
        8.61930370e-01,  1.33258307e+00,  1.95459589e-01, -6.18712366e-01,
        1.24757063e+00,  1.33161783e+00,  3.24424207e-01,  1.13412464e+00,
        3.32053393e-01,  1.01110125e+00,  3.96239519e-01,  1.16403925e+00,
        3.29725921e-01,  1.33049870e+00,  6.46832466e-01,  1.33055973e+00,
        4.04128760e-01,  2.19638750e-01,  1.07669985e+00,  3.29080731e-01,
        3.31849754e-01,  3.24329287e-01,  8.18219066e-01,  1.25696945e+00,
        1.14936614e+00,  1.29935527e+00,  1.32816815e+00,  3.29637378e-01,
        1.22598159e+00,  3.30737442e-01,  1.17378664e+00,  9.98954594e-01,
        1.21651053e+00,  3.31828058e-01,  3.31654847e-01,  1.20288670e+00,
        3.31576377e-01,  1.15648508e+00,  5.31440377e-01,  1.22698212e+00,
        1.32860875e+00,  3.30530286e-01,  8.52134466e-01,  1.08588338e+00,
        1.11176276e+00, -3.52780461e-01,  1.15534294e+00,  1.33107483e+00,
        3.29151988e-01,  1.10183370e+00,  3.30077231e-01,  1.16412508e+00,
        9.97913957e-01,  1.27178514e+00,  3.31638217e-01,  3.30453485e-01,
        1.12691689e+00,  3.31280023e-01,  8.54029655e-01,  3.61303091e-01,
        1.24489498e+00,  3.31946343e-01,  3.25450897e-01,  7.37142861e-01,
        3.31340164e-01,  1.18118572e+00,  8.63350272e-01,  1.26921022e+00,
        3.32228482e-01,  3.30055267e-01,  1.20391583e+00,  3.32455844e-01,
       -2.63596535e-01, -3.84038377e+00,  9.03440595e-01,  1.33266568e+00,
        3.29978228e-01, -1.36615276e+00,  1.33181679e+00,  1.10324049e+00,
        1.12519336e+00,  1.25613260e+00,  1.33177793e+00,  1.33045447e+00,
        1.22119749e+00,  3.30097109e-01,  1.27219319e+00,  4.33220476e-01,
        1.28243005e+00,  3.31917375e-01,  3.32006425e-01,  1.21939290e+00,
        3.32046121e-01,  1.19106793e+00,  5.29094398e-01,  1.24510741e+00,
        1.32924712e+00,  3.32021803e-01,  1.12703621e+00,  1.15780008e+00],
      dtype=float32)

In [14]:
num_llms = 7
SOFTMAX_TEMPERATURE = 1.0
utility_reshaped = utility_list.reshape(-1, num_llms) / SOFTMAX_TEMPERATURE
utility_reshaped

array([[ 2.86612213e-01, -2.65735090e-01,  2.38420531e-01,
         1.33153558e+00,  3.30783755e-01,  2.47376442e-01,
         3.13575834e-01],
       [ 2.16807097e-01, -9.80435610e-01,  1.71236560e-01,
         1.33137298e+00,  1.33004844e+00,  1.20127141e+00,
         1.30528224e+00],
       [ 2.15351030e-01, -6.03930891e-01,  1.27695918e-01,
         3.32691073e-01,  3.30899507e-01,  2.68264115e-01,
         3.30785602e-01],
       [ 1.21945786e+00,  2.78333724e-01,  1.10919797e+00,
         3.32728237e-01,  3.30041587e-01,  3.24955732e-02,
         2.90302843e-01],
       [ 1.26425862e+00,  1.21454120e+00,  1.27155805e+00,
         1.32555819e+00,  1.32704103e+00,  1.25782645e+00,
         3.13551426e-01],
       [ 1.25015557e+00,  7.08641231e-01,  1.25199986e+00,
         3.32814276e-01,  3.28209281e-01,  1.22744668e+00,
         1.29980445e+00],
       [ 1.47536650e-01,  7.75919437e-01,  1.08020163e+00,
         1.32810223e+00,  3.31502885e-01,  1.09791017e+00,
         1.22963345e+00],
       [ 1.75550237e-01,  2.26218104e-01,  1.79758862e-01,
         1.33048785e+00,  3.26230764e-01,  1.76268935e-01,
         3.27849448e-01],
       [ 1.27447641e+00,  1.29416919e+00,  1.28252316e+00,
         3.31766754e-01,  1.32948446e+00,  1.29358852e+00,
         3.28482270e-01],
       [ 1.17287612e+00, -5.21478117e-01,  1.27279431e-01,
         3.29870820e-01,  3.30760121e-01, -4.07829918e-02,
         2.47538373e-01],
       [ 1.77832931e-01,  3.86964232e-01,  1.18651426e+00,
         1.32896650e+00,  1.33133852e+00,  1.06557882e+00,
         3.30167443e-01],
       [ 1.25060928e+00,  1.22004986e+00,  1.28417170e+00,
         1.33088827e+00,  1.33120489e+00,  1.21196461e+00,
         1.33090830e+00],
       [ 1.93196848e-01,  2.84211814e-01,  4.38739136e-02,
         3.32141429e-01,  3.31812114e-01,  2.78272063e-01,
         3.28736752e-01],
       [ 1.73753873e-01, -1.77083600e+00,  3.66379172e-02,
         3.32100034e-01,  3.30012560e-01,  5.46997070e-01,
         3.29940706e-01],
       [ 1.56126052e-01,  4.17077065e-01,  1.18904546e-01,
         3.29443574e-01,  3.28013659e-01, -8.76092374e-01,
         1.97512254e-01],
       [ 1.67539522e-01, -2.67968845e+00,  3.78886797e-02,
         3.30838680e-01,  3.30559433e-01,  2.61727035e-01,
         1.32819843e+00],
       [ 1.24198604e+00, -7.18963027e-01,  1.20385444e+00,
         1.32943583e+00,  3.28782111e-01, -3.89737725e-01,
         1.32854819e+00],
       [ 1.91457629e-01, -2.73036695e+00,  3.49757224e-02,
         3.27860981e-01,  1.32887113e+00, -4.97891092e+00,
         1.32994676e+00],
       [ 1.88711271e-01, -1.41708672e+00,  1.15334082e+00,
         3.29391241e-01,  3.30604851e-01, -2.11748052e+00,
         3.17330956e-01],
       [ 1.14586949e+00, -5.31023502e-01,  4.03884389e-02,
         3.27256799e-01,  3.26690614e-01, -5.74362946e+00,
         1.32764161e+00],
       [ 1.10808842e-01,  1.51853114e-01,  1.15026975e+00,
         1.33047748e+00,  3.28614771e-01,  1.11769879e+00,
         2.01742023e-01],
       [ 1.19041848e+00,  9.00815666e-01,  1.24241650e+00,
         3.30331326e-01,  3.30448359e-01,  1.16740012e+00,
         1.27276623e+00],
       [ 1.61611751e-01, -2.94329971e-01,  4.64397632e-02,
         3.31114054e-01,  3.30036849e-01, -3.20694625e-01,
         3.30585897e-01],
       [ 1.49221003e-01, -3.11852407e+00,  3.10307331e-02,
         3.31626564e-01,  3.29137862e-01, -3.40812659e+00,
         3.29216182e-01],
       [ 9.29828547e-03,  3.09681118e-01,  3.32269482e-02,
         3.30550551e-01,  3.29369962e-01,  9.46085274e-01,
         3.25795084e-01],
       [ 1.21747935e+00,  1.21684992e+00,  1.25804901e+00,
         3.20073843e-01,  3.25502187e-01,  1.21312463e+00,
         2.99030870e-01],
       [ 1.20681846e+00, -5.33938527e-01,  1.17418730e+00,
         1.32924819e+00,  3.20214748e-01,  1.04566026e+00,
         2.65886486e-01],
       [ 1.12667847e+00,  3.11074048e-01,  3.88985500e-02,
         3.30754369e-01,  3.18747520e-01,  1.07876647e+00,
         1.83725327e-01],
       [ 1.40469953e-01, -1.37772393e+00,  1.04445171e+00,
         3.28158408e-01,  3.30065459e-01,  4.16683674e-01,
         3.28586519e-01],
       [ 1.21953857e+00,  8.37573290e-01,  1.14872479e+00,
         3.32348764e-01,  3.31439555e-01,  1.17731237e+00,
         3.07257682e-01],
       [ 1.10468876e+00, -1.38352001e+00,  3.56811285e-02,
         3.31328362e-01,  3.30577821e-01, -6.32927835e-01,
         3.30522865e-01],
       [ 1.17958319e+00,  2.16215163e-01,  1.13565397e+00,
         3.30672294e-01,  3.31794262e-01,  1.10384440e+00,
         2.99182832e-01],
       [ 1.67449847e-01, -1.47398770e+00, -2.87424680e-02,
         3.31472605e-01,  3.31019074e-01, -1.02043355e+00,
         3.30878705e-01],
       [ 1.39764354e-01, -1.12848125e-01,  3.26266050e-01,
         3.31783742e-01,  3.31607848e-01,  6.93933129e-01,
         3.31394136e-01],
       [ 1.74541742e-01,  8.83691758e-02,  1.12472618e+00,
         3.32511187e-01,  3.31954062e-01,  8.88486326e-01,
         3.30444962e-01],
       [ 1.13630366e+00, -8.92607346e-02,  8.73798728e-01,
         3.27762157e-01,  3.30619305e-01,  7.00587511e-01,
         3.31156254e-01],
       [ 1.12443793e+00,  2.04552382e-01,  1.23513472e+00,
         3.27408880e-01,  3.30860466e-01,  1.11658883e+00,
         3.29492509e-01],
       [ 9.93431926e-01, -7.48878717e-02,  9.88871932e-01,
         1.33027661e+00,  3.29183161e-01,  1.04896045e+00,
         3.28227639e-01],
       [ 9.01319366e-03, -1.51013088e+00,  1.13121498e+00,
         3.31632316e-01,  3.31420660e-01,  2.29348049e-01,
         3.32418859e-01],
       [ 1.23821795e+00,  1.09124327e+00,  1.26918650e+00,
         3.31278861e-01,  3.31364006e-01,  1.28508317e+00,
         3.30404848e-01],
       [ 9.58021462e-01,  6.61173165e-01,  1.21676672e+00,
         3.30133736e-01,  3.29681695e-01,  1.17198408e+00,
         3.29212219e-01],
       [ 1.16885960e+00, -2.17801821e-03,  1.27840447e+00,
         1.33083117e+00,  3.28311354e-01,  1.13957930e+00,
         3.29232931e-01],
       [ 1.11545169e+00,  4.70694721e-01,  1.24400842e+00,
         3.28819275e-01,  3.29965323e-01,  1.27095366e+00,
         3.31011981e-01],
       [ 2.58303881e-01, -1.26599863e-01,  9.32760835e-01,
         3.29715729e-01,  3.32570195e-01,  2.69272357e-01,
         7.81350061e-02],
       [ 1.21961808e+00,  6.24305785e-01,  1.28551686e+00,
         3.29342335e-01,  3.29419941e-01,  1.24923754e+00,
         3.30887198e-01],
       [ 9.96774435e-01,  7.22455084e-01,  1.22737002e+00,
         3.30480605e-01,  3.32065463e-01,  1.06583416e+00,
         3.30694616e-01],
       [ 9.24683392e-01,  7.83174932e-01,  1.19755125e+00,
         3.31075191e-01,  3.29112172e-01,  1.10500085e+00,
         3.32567632e-01],
       [ 7.34348297e-01,  4.37614948e-01,  1.14639628e+00,
         1.33223283e+00,  3.30696195e-01,  8.07826698e-01,
         3.31149697e-01],
       [ 1.11857605e+00,  7.52082944e-01,  1.23187268e+00,
         3.31374735e-01,  3.31252366e-01,  8.78899813e-01,
         3.29228669e-01],
       [ 1.16821110e+00, -4.00026031e-02,  1.18307602e+00,
         1.33157587e+00,  3.29177499e-01,  6.66742980e-01,
         3.29684138e-01],
       [ 1.09620798e+00,  9.48160708e-01,  1.23173761e+00,
         1.33282733e+00,  3.32343519e-01,  1.11756110e+00,
         3.31084013e-01],
       [ 3.82490898e-03, -9.28536475e-01,  1.01981664e+00,
         1.33202970e+00,  3.31755280e-01, -3.13362367e-02,
         3.28937978e-01],
       [-3.16291809e-01, -4.99754436e-02,  1.18252888e-01,
         1.32382321e+00,  3.29965055e-01,  2.80159891e-01,
         1.33086729e+00],
       [ 1.24700809e+00,  8.00206423e-01,  1.26493764e+00,
         1.32792115e+00,  3.30624759e-01,  1.24749005e+00,
         3.31747055e-01],
       [-3.81918073e-01, -3.86015129e+00,  7.70686328e-01,
         1.33060980e+00,  3.29855561e-01, -4.21654172e-02,
         3.31539303e-01],
       [ 1.25573647e+00,  1.21812522e+00,  1.30588090e+00,
         1.33000934e+00,  3.29919904e-01,  1.27152240e+00,
         1.32835591e+00],
       [ 1.21193421e+00,  8.53848338e-01,  1.26952064e+00,
         1.33020902e+00,  3.32253784e-01,  1.20402861e+00,
         1.32226491e+00],
       [-3.18025917e-01, -2.78223109e+00,  9.66265559e-01,
         1.33110762e+00,  3.29731375e-01,  2.92577684e-01,
         3.29290360e-01],
       [ 1.21906757e+00,  1.00429356e+00,  1.28079307e+00,
         3.22897196e-01,  3.30838889e-01,  1.25444698e+00,
         3.29979926e-01],
       [ 1.07450950e+00,  8.13667834e-01,  1.30386448e+00,
         1.33142602e+00,  1.33048856e+00,  1.22296345e+00,
         1.33062720e+00],
       [ 1.11910772e+00,  4.78674412e-01,  1.20440698e+00,
         1.33147967e+00,  1.33153808e+00,  9.20976758e-01,
         3.30676675e-01],
       [ 1.08833432e+00,  8.45157981e-01,  1.18671715e+00,
         3.28875542e-01,  3.32370877e-01,  8.61930370e-01,
         1.33258307e+00],
       [ 1.95459589e-01, -6.18712366e-01,  1.24757063e+00,
         1.33161783e+00,  3.24424207e-01,  1.13412464e+00,
         3.32053393e-01],
       [ 1.01110125e+00,  3.96239519e-01,  1.16403925e+00,
         3.29725921e-01,  1.33049870e+00,  6.46832466e-01,
         1.33055973e+00],
       [ 4.04128760e-01,  2.19638750e-01,  1.07669985e+00,
         3.29080731e-01,  3.31849754e-01,  3.24329287e-01,
         8.18219066e-01],
       [ 1.25696945e+00,  1.14936614e+00,  1.29935527e+00,
         1.32816815e+00,  3.29637378e-01,  1.22598159e+00,
         3.30737442e-01],
       [ 1.17378664e+00,  9.98954594e-01,  1.21651053e+00,
         3.31828058e-01,  3.31654847e-01,  1.20288670e+00,
         3.31576377e-01],
       [ 1.15648508e+00,  5.31440377e-01,  1.22698212e+00,
         1.32860875e+00,  3.30530286e-01,  8.52134466e-01,
         1.08588338e+00],
       [ 1.11176276e+00, -3.52780461e-01,  1.15534294e+00,
         1.33107483e+00,  3.29151988e-01,  1.10183370e+00,
         3.30077231e-01],
       [ 1.16412508e+00,  9.97913957e-01,  1.27178514e+00,
         3.31638217e-01,  3.30453485e-01,  1.12691689e+00,
         3.31280023e-01],
       [ 8.54029655e-01,  3.61303091e-01,  1.24489498e+00,
         3.31946343e-01,  3.25450897e-01,  7.37142861e-01,
         3.31340164e-01],
       [ 1.18118572e+00,  8.63350272e-01,  1.26921022e+00,
         3.32228482e-01,  3.30055267e-01,  1.20391583e+00,
         3.32455844e-01],
       [-2.63596535e-01, -3.84038377e+00,  9.03440595e-01,
         1.33266568e+00,  3.29978228e-01, -1.36615276e+00,
         1.33181679e+00],
       [ 1.10324049e+00,  1.12519336e+00,  1.25613260e+00,
         1.33177793e+00,  1.33045447e+00,  1.22119749e+00,
         3.30097109e-01],
       [ 1.27219319e+00,  4.33220476e-01,  1.28243005e+00,
         3.31917375e-01,  3.32006425e-01,  1.21939290e+00,
         3.32046121e-01],
       [ 1.19106793e+00,  5.29094398e-01,  1.24510741e+00,
         1.32924712e+00,  3.32021803e-01,  1.12703621e+00,
         1.15780008e+00]], dtype=float32)

In [15]:
utility_reshaped[0]

array([ 0.2866122 , -0.2657351 ,  0.23842053,  1.3315356 ,  0.33078375,
        0.24737644,  0.31357583], dtype=float32)

In [15]:
edge_features[0]

array([ 0.        , -0.27179012, -0.30002776, -0.10013796, -0.34709436,
        1.        ,  0.        ,  0.        ,  1.        ], dtype=float32)

In [26]:
import pandas as pd
import numpy as np

def calculate_query_utility(
    query_id: str | int,
    df: pd.DataFrame,
    weights: dict = None
) -> pd.DataFrame:
    """
    Calculates utility scores across all models for a specific query ID using
    exact dataset column names.

    Parameters:
    -----------
    query_id : str or int
        Unique identifier for the target query.
    df : pd.DataFrame
        DataFrame containing query benchmarking records across candidate models.
    weights : dict, optional
        Utility weights matching config.yaml specifications.

    Returns:
    --------
    pd.DataFrame
        Table of candidate models ranked by calculated utility score.
    """
    # Default weights matching config.yaml
    if weights is None:
        weights = {
            'w_success': 1.0,
            'w_cost': 0.3,
            'w_latency': 0.3,
            'w_output_tokens': 0.2,
            'w_completion_reliability': 0.5
        }

    # Filter dataframe for the given query
    query_df = df[df['query_id'] == query_id].copy()
    if query_df.empty:
        raise ValueError(f"Query ID '{query_id}' not found in the dataset.")

    # Extract key metric series using exact column names
    success = query_df['Correct'].astype(float)
    cost = query_df['Cost'].astype(float)
    latency = query_df['Latency'].astype(float)
    out_tokens = query_df['Output_Tokens'].astype(float)

    # Reliability: 1.0 if status indicates success/completion, otherwise 0.0
    reliability = query_df['Completion_Status'].apply(
        lambda x: 1.0 if x in [1, True, 'Success', 'SUCCESS', 'Completed', 'completed'] else (float(x) if str(x).replace('.','',1).isdigit() else 0.0)
    )

    # Per-query min-max normalization function for penalty metrics
    def min_max_norm(series: pd.Series) -> pd.Series:
        rng = series.max() - series.min()
        return (series - series.min()) / rng if rng > 0 else pd.Series(0.0, index=series.index)

    # Calculate normalized penalties relative to candidate models for this query
    cost_norm = min_max_norm(cost)
    latency_norm = min_max_norm(latency)
    out_tokens_norm = min_max_norm(out_tokens)

    # Utility score calculation
    query_df['utility_score'] = (
        weights['w_success'] * success
        + weights['w_completion_reliability'] * reliability
        - weights['w_cost'] * cost_norm
        - weights['w_latency'] * latency_norm
        - weights['w_output_tokens'] * out_tokens_norm
    )

    # Select key summary columns and sort by highest utility score
    display_cols = [
        'model', 'utility_score', 'Correct', 'Cost',
        'Latency', 'Output_Tokens', 'Completion_Status'
    ]

    result = (
        query_df[display_cols]
        .sort_values(by='utility_score', ascending=False)
        .reset_index(drop=True)
    )

    return result

In [27]:
router_df

,row_id,query_id,task_description,task_description_embedding,query,query_embedding,Gold_Answer,Answer_Type,model,Predicted_Answer,...,Output_Tokens,Total_Tokens,Cost,Latency,Completion_Status,Error_Type,Final_Answer_Length,Timestamp,reasoning_score,response
0,d6e6c6d24304,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,anthropic/claude-sonnet-4-5,336,...,221,403,0.003861,6.291,success,wrong_answer,3,2026-06-22T11:33:44.699876+00:00,NaN,I need to find the number of ways to divide 10...
1,5832db75e144,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,deepseek/deepseek-r1,336,...,5841,5998,0.014712,204.084,success,wrong_answer,3,2026-06-22T12:52:07.306918+00:00,NaN,The number of ways to divide 10 distinct girls...
2,acca4d08183e,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,google/gemini-3.5-flash,336,...,786,948,0.007317,5.973,success,wrong_answer,3,2026-06-22T12:51:49.776277+00:00,NaN,FINAL_ANSWER:\n336
3,00c055cf04a2,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,meta-llama/llama-3.1-70b-instruct,\binom{10}{4} + \binom{10}{5},...,22,183,0.000073,1.730,success,none,29,2026-06-22T11:35:06.160700+00:00,NaN,FINAL_ANSWER: \binom{10}{4} + \binom{10}{5}
4,3a780bd77dc7,44b2b96644c6,Divisibility + Pairwise Coprimality / Constrai...,"[[-0.004198932554572821, 0.067597396671772, -0...",The group of 10 girls should be divided into t...,"[[0.008862393908202648, -0.01544900517910719, ...",462,latex,mistralai/mixtral-8x22b-instruct,115,...,11,186,0.000167,1.981,success,wrong_answer,3,2026-06-22T11:35:20.612191+00:00,NaN,FINAL_ANSWER:\n115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,84a94d01efc4,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,google/gemini-3.5-flash,540,...,747,892,0.006940,4.365,success,none,3,2026-07-01T00:47:14.814064+00:00,NaN,FINAL_ANSWER:\n540
528,c0fbd2d28827,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,meta-llama/llama-3.1-70b-instruct,\sqrt{117^2+144^2}+75\cdot4,...,21,163,0.000065,3.502,success,none,27,2026-07-01T00:47:49.400257+00:00,NaN,FINAL_ANSWER:\n\sqrt{117^2+144^2}+75\cdot4
529,a938cced6691,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,mistralai/mixtral-8x22b-instruct,135,...,11,167,0.000150,1.170,success,wrong_answer,3,2026-07-01T00:47:54.936346+00:00,NaN,FINAL_ANSWER:\n135
530,adb08f542d48,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,openai/gpt-5,540,...,1420,1560,0.014375,28.248,success,none,3,2026-06-30T23:27:38.981802+00:00,NaN,FINAL_ANSWER:\n540
531,a1718526e127,2347acb5eb3b,Olympiad Reasoning,"[[-0.00014781509526073933, 0.14556902647018433...",Find the largest possible real part of \[(75+1...,"[[0.018808305263519287, 0.11890657246112823, -...",540,latex,qwen/qwen3-235b-a22b,NaN,...,2731,2877,0.005037,30.160,success,none,0,2026-07-01T00:47:19.210218+00:00,NaN,To find the **largest possible real part** of ...

In [32]:
router_df.query_id.unique()

array(['44b2b96644c6', '2ccbe9e61ecf', '6d70005c9303', 'df7389706c09',
       'b1ea61565b4e', '619336412192', '321d86ce79e1', 'b3861445cc06',
       'd399e6ff9ba0', 'fa1f02a208b2', '98a313a86f15', 'f5c44c1f20cd',
       'da25610ff924', 'ba9152f3d981', 'a17f289c902d', 'e21531fb7bff',
       'dd187547d811', '93ee90bd4810', 'ba20256f2d8f', '552752099497',
       '2822569975bb', 'f3d797442d90', '5e99c1f8e33f', '5cc894a0e8a6',
       'ac19f76765b0', '4d866680f923', 'b80bbab3f94d', 'e6ea64827cab',
       'f2f2d976fb29', '77bffe9f7e54', 'bce9ef2f43a9', 'f3d7b78d243a',
       'f969f616feb3', '9cdfb2e553b3', '6fda1b293f84', 'c4ae027f8486',
       '6a5b9b9200b7', 'fd14e1d88f3a', 'a69cadd900e6', '9e41363fe398',
       '1ee995a8d3c7', '11b94562acc8', 'c44d2bf7affb', '7108276b8fa4',
       'cdb9abd4f7a1', '7968ea2f49d4', '9a742f03e053', 'b55b05e56d89',
       '2813fc865fdb', 'ad13376b6795', 'c2359e2c8745', '80a7415f3d3c',
       'c3c962ab1ff1', '0e2fbc9ece85', '95aedf7c6ac6', '75e19ca5a482',
       '7c7a6fffd9fc', 'fe0941895f63', '4651f80b300c', '374d0036d9ad',
       '1df7fa289d98', '66701717f496', 'f8054f349b61', 'e39fa031935e',
       '27e40ddeea86', '58fe1199c927', 'ebcd91c8dffa', '5f36a2e00d92',
       'b20f21736ec1', '0e03c895efad', '5dd725c2220d', 'f4fc4878eb16',
       '2ca69081aefc', '978a60d52863', '43afc8d2eb63', '2347acb5eb3b'],
      dtype=object)

In [43]:
# Custom weights if needed (or pass None to use defaults)
custom_weights = {
    'w_success': 1.0,
    'w_cost': 0.6,
    'w_latency': 0.3,
    'w_output_tokens': 0.2,
    'w_completion_reliability': 0.0
}

# Calculate utility scores across models for query ID 'Q_104'
utility_table = calculate_query_utility(query_id="77bffe9f7e54", df=router_df, weights=custom_weights)
print(utility_table)

                               model  utility_score  Correct      Cost  \
0        anthropic/claude-sonnet-4-5       0.546856        1  0.009678
1                       openai/gpt-5       0.458181        1  0.010765
2            google/gemini-3.5-flash       0.318548        1  0.014018
3  meta-llama/llama-3.1-70b-instruct      -0.000128        0  0.000073
4   mistralai/mixtral-8x22b-instruct      -0.004737        0  0.000180
5               deepseek/deepseek-r1      -0.019699        1  0.012151
6               qwen/qwen3-235b-a22b      -0.054705        0  0.000793

   Latency  Output_Tokens Completion_Status
0    9.509            619           success
1   22.681           1062           success
2   11.380           1538           success
3    1.437             10           success
4    1.365             13           success
5  169.790           4814           success
6    5.761            392           success